### ISSUE TITLE
Falsche Darstellung in Safari

### ISSUE THREAD

**Issue by jankout** [fritzmg/contao-lightcase#1]
Hallo Fritz, ich habe am Macbook Air in Safari festgestellt, dass die Darstellung falsch ist. Ich habe den Entwickler auch bereits kontaktiert. Siehe https://github.com/cbopp-art/lightcase/issues/138 In anderen Browsern tritt es nicht auf. Sollen wir das im Forum besprechen?

**Comment by fritzmg** [comment]
Eher Forum und eben in https://github.com/cbopp-art/lightcase/issues/138

**Comment by jankout** [comment]
ok.

**Comment by jankout** [comment]
https://community.contao.org/de/showthread.php?67637-Contao-lightcase&p=447586#post447586
