### ISSUE TITLE
double-click behavior 

### ISSUE THREAD

**Issue by bennie99** [fritzmg/contao-lightcase#4]
Referring to [this Post](https://community.contao.org/de/showthread.php?81049-Contao-Lightcase-Doppelklick-auf-prev-next-ruft-Starseite-auf) in ContaoCommunity.
Double-Click on prev or next causes the homepage to start
How to avoid this? No Problems in Original Demo.

**Comment by fritzmg** [comment]
I cannot reproduce the problem. My guess is something else on your site is interfering.

**Comment by fritzmg** [comment]
See https://github.com/cbopp-art/lightcase/issues/187
